### ISSUE TITLE
H/L keys for switching between focusing hit and file view

### ISSUE THREAD

**Issue by quchen** [fmthoma/vgrep#2]
Keybindings right now:
- <kbd>Tab</kbd>: Toggle between hit view/file content view
- <kbd>Enter</kbd>: Focus content view
- <kbd>Esc</kbd>: Focus hit view
- <kbd>j</kbd>, <kbd>k</kbd>: Scroll down/up in current view

I think having <kbd>h</kbd>/<kbd>l</kbd> to focus left/right view would make a vim-intuitive addition to this.

Possible conflict: scrolling left and right in the content view would require the same keys.

**Comment by fmthoma** [comment]
Yep, I'd rather have them scroll left and right in the pager. I'm still considering a 'stacking' behavior like tig, where <kbd>Enter</kbd> opens a split view and <kbd>q</kbd> closes it again (without the stupid overloaded <kbd>j</kbd><kbd>k</kbd>/<kbd>↓</kbd><kbd>↑</kbd> keybindings, of course).
