### ISSUE TITLE
Could not load cached data

### ISSUE THREAD

**Issue by gbin** [fmthoma/vgrep#43]
I am on arch, installed vgrep from the AUR install script.
Whatever I do except --help, vgrep tells me "
```
$ ag t |vgrep
Could not load cached data
```
I straced it trying to open `~/.config/vgrep`

created the directory manually with `mkdir ~/.cache/vgrep` but still no luck.

Any clue about what is going on ?
Thanks.

**Comment by fmthoma** [comment]
That's an odd error message, since `vgrep` does not cache any data. What version of `vgrep` are you using (`vgrep --version`)?

**Comment by fmthoma** [comment]
@gbin Closing this for now.
