### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by kuwze** [fmthoma/vgrep#45]
I am running Ubuntu 17.04, I just installed stack `Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682ecfd694e (4861 commits) x86_64 hpack-0.17.1`, `stack setup` installed `ghc-nopie-8.0.2.`, but when I run `stack install vgrep` I get:

> Error: While constructing the build plan, the following exceptions were encountered:
> 
> In the dependencies for vgrep-0.2.0.0:
>     aeson-1.1.2.0 must match (>=0.11 && <1.0) || (>=0.9 && <0.10) (latest applicable is 0.11.3.0)
> needed for unknown reason - stack invariant violated.
> 
> Plan construction failed.
>

**Comment by chrissound** [comment]
Set your stack resolver to `lts-9.0` within `~/.stack/global-project/stack.yaml`.

**Comment by fmthoma** [comment]
@kuwze Version 2.0 is not forward-compatible to Stackage LTS 9.x. I have published a release `vgrep-0.2.1.0` which should fix the issue, so `stack update && stack install vgrep` should work again.
