### ISSUE TITLE
Build failure with Cabal-3.0.0.0

### ISSUE THREAD

**Issue by sjakobi** [fmthoma/vgrep#53]
Due to https://github.com/nkpart/cabal-file-th/issues/10.

It seems that `cabal-file-th` is used only to access the package name and version:

https://github.com/fmthoma/vgrep/blob/a5c3aa598f25040dde9fa6fc000854d98329ef46/app/Main.hs#L82-L83

At least the version could alternatively be accessed via the `Paths_vgrep` module. The name could possibly be hardcoded?!

**Comment by fmthoma** [comment]
Thanks for the hint with `Paths_vgrep`!
